services:
  # serviço mysql
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - ./mysql-data:/var/lib/mysql
  # serviço apache e php
  web:
    build: .
    container_name: web-container
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    # garante que o apache e php suba depois do mysql
    depends_on:
      - mysql
  # serviço phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    ports:
      - "8081:80"
    environment:
      # endereço do servidor mysql, nesse caso informamos o nome do serviço
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    # garantir que o phpmyadmin suba depois do mysql
    depends_on:
      - mysql
